# Generated by Django 5.2.5 on 2025-08-06 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Video', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videomodel',
            name='video_file',
        ),
        migrations.AddField(
            model_name='videomodel',
            name='hls_folder',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='videomodel',
            name='original_file',
            field=models.FileField(default=1, upload_to='original_videos/'),
            preserve_default=False,
        ),
    ]
